; Modbus TCP easyE4
[Communication0]
Description=Bureau
Type=16
Group=3
Model=4
Endianness=0
TwistedOrder=1
Alignment=3
ComDeviceName=eth
LifeTimeCycle=10
Parameter1=0		; Address Offset
Parameter2=502		; Port Number
Parameter4=1		; Default Unit Identifier
String1="192.168.0.51"		; IP Address or Hostname
Break=0
StartupDelay=5
MinCycleTime=50

